In [1]:
import numpy as np


In [4]:
# build the class of MLP


class MLP:
    
    def __init__(self, num_inputs=3, num_hidden=[3, 5], num_outputs=2):
        
        self.num_inputs = num_inputs
        self.num_hidden = num_hidden
        self.num_outputs = num_outputs
        
        
        layers = [self.num_inputs] + self.num_hidden + [self.num_outputs]
        
        # initiate random weights
        self.weights = []
        
        # create weights matrices for each two subsequent layers in the MLP architecture
        for i in range(len(layers)-1):
            w = np.random.rand(layers[i], layers[i+1])
            self.weights.append(w)
            
    
    def forward_propagate(self, inputs):
        
        activations = inputs
        
        for w in self.weights:
            # calculate net inputs
            net_inputs = np.dot(activations, w)
        
            # calculate the activations
            activations = self._sigmoid(net_inputs)
        
        return activations
    
    
    def _sigmoid(self, x):
        return 1/(1 + np.exp(-x))

In [5]:
mlp = MLP()

inputs = np.random.rand(mlp.num_inputs)

output = mlp.forward_propagate(inputs)

print(inputs, output)

[0.23166939 0.99505063 0.56693334] [0.85822931 0.89268297]


In [6]:
mlp.weights

[array([[0.72710192, 0.9732658 , 0.4867014 ],
        [0.68513625, 0.3613799 , 0.04730775],
        [0.70226945, 0.60082526, 0.84729453]]),
 array([[0.62551885, 0.72825221, 0.90793098, 0.72033902, 0.17680321],
        [0.57589463, 0.29571383, 0.84027589, 0.17464583, 0.19593625],
        [0.08335056, 0.05957612, 0.05779832, 0.54067301, 0.56997644]]),
 array([[0.06248954, 0.45764739],
        [0.75112079, 0.91006899],
        [0.66130042, 0.80595545],
        [0.74847964, 0.60260046],
        [0.23913258, 0.11031879]])]

In [8]:
mlp.weights[2].shape

(5, 2)